name: Build Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.14' # Quotes required to prevent YAML converting to number
      - name: Install Nats Server
        uses: synadia-io/workflows/.github/actions/install_nats_server@main
      - name: Check out code
        uses: actions/checkout@v5
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test jacocoTestReport
      - name: Verify Javadoc
        run: ./gradlew javadoc
      - name: Send coverage to Coveralls
        continue-on-error: true
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Clean up
        if: always()
        run: pkill -9 nats-server 2>/dev/null || true
